# YAML file for running POD-LSTM training, testing, data assimilation

# Location of various training/testing data
data_paths:
  # For raw training and testing
  training_coefficients: 'data/Z500/Training_Coefficients.npy'
  training_mean: 'data/Z500/Training_mean.npy'
  pod_modes: 'data/Z500/POD_Modes.npy'
  testing_coefficients: 'data/Z500/Testing_Coefficients.npy'

  # For testing
  training_fields: 'data/Z500/Training_snapshots.npy'
  testing_fields: 'data/Z500/Testing_snapshots.npy'

  # Variational data assimilation
  da_testing_fields: 'data/Z500/Testing_snapshots.npy'

  # Save locations
  save_path: 'results/Z500/'

  # Coordinate paths
  cood_path: 'data/Z500/'

  # Regional analyses
  subregions:
    - 'data/subregions/Alaska_coarse.nc'
    - 'data/subregions/Midwest_coarse.nc'
    - 'data/subregions/NGreatPlains_coarse.nc'
    - 'data/subregions/Northeast_coarse.nc'
    - 'data/subregions/Northwest_coarse.nc'
    - 'data/subregions/SGreatPlains_coarse.nc'
    - 'data/subregions/Southeast_coarse.nc'
    - 'data/subregions/Southwest_coarse.nc'

operation_mode:
  train: True
  test: True # Perform test forecasts
  perform_var: False # Perform 3D Var
  perform_analyses: True # Perform analyses on finished forecasts

hyperparameters:
  - 5000 # num_observations
  - 31 #input window
  - 21 #output window
  - 0.7 # Train-valid split
  - 365 # 3D Var duration in test regime
  - 200 # Number of LSTM training epochs
  - 20 # Number of POD modes to truncate
